version: '3'
services:
  postgres:
    image: postgres:15-alpine
    container_name: boardgameshub-db
    environment:
      POSTGRES_DB: boardgameshub-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./boardgameshub/src/main/resources/db/:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    restart: unless-stopped
  cassandra:
    image: cassandra:4
    ports:
      - 9042:9042
    volumes:
      - ./resources:/resources
      - ./boardgameshub/src/main/resources/init_keyspace.cql:/docker-entrypoint-initdb.d/init_keyspace.cql
  springboot:
    depends_on:
      - postgres
      - cassandra
    build:
      context: ./boardgameshub
      dockerfile: Dockerfile
    volumes:
      - ./boardgameshub:/app
      - ./.m2:/root/.m2
    working_dir: /app
    command: sh -c "./wait-for-it.sh cassandra:9042 -t 70 && sh run.sh"
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
volumes:
  pgdata:
    driver: local
