FROM node:14 as build

WORKDIR /webApp

COPY package.json .
COPY package-lock.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:1.24-alpine

COPY nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=build /webApp/build /usr/share/nginx/html

EXPOSE 3000
